[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.23"
evm_version = 'shanghai'
optimizer = true
optimizer_runs = 20_000

[rpc_endpoints]
devnet = "${DEVNET_RPC_URL}"
fantom = "${MAINNET_RPC_URL}"

[etherscan]
fantom = { key = "${MAINNET_ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config